batch:
  input_dir: "data/prototype/microlensing_final"
  output_dir: "data/prototype/microlensing_final/results"
  pattern: "*.asdf"

pipeline:
  - type: load_image
  - type: photometry
    model_path: "models/stage0/stage0_f48faa6.onnx"
    threshold: 0.5
    batch_size: 64
  - type: save_catalog
  - type: database_upload
    database_path: "data/prototype/microlensing_final.db"
    clobber: true
    match_radius_arcsec: 1.0
