batch:
  input_dir: "/home/dylan/castor/data/microlensing_example"
  output_dir: "/home/dylan/castor/data/microlensing_example/results"
  pattern: "epoch_*.asdf"

pipeline:
  - type: load_image
  - type: photometry
    model_path: "models/stage0/stage0_78d8c11.onnx"
    threshold: 0.43
    batch_size: 64
  - type: save_catalog
  - type: database_upload
    database_path: "/home/dylan/castor/data/microlensing_example/microlensing_final.db"
    clobber: true
    match_radius_arcsec: 1.0
